web:
    resource: ../../src/Controller/Web/
    type: attribute
    prefix: /

admin:
    resource: ../../src/Controller/Admin/
    type: attribute
    prefix: /admin

auth:
    resource: ../../src/Controller/Security/
    type: attribute
    prefix: /auth

kernel:
    resource: ../../src/Kernel.php
    type: attribute
cargo:
    path: /user/cargo
    controller: App\Controller\CargoController::index